package oci

// Shared test fixture constants. These values are repeated across many test
// files in this package; naming them keeps the fixtures consistent and
// satisfies the goconst linter.
const (
	// Version tags.
	testTagV001   = "v0.0.1"
	testTagV010   = "v0.1.0"
	testTagV030   = "v0.3.0"
	testTagV050   = "v0.5.0"
	testTagV090   = "v0.9.0"
	testTagV100   = "v1.0.0"
	testTagV110   = "v1.1.0"
	testTagV120   = "v1.2.0"
	testTagV150   = "v1.5.0"
	testTagV200   = "v2.0.0"
	testTagV230   = "v2.3.0"
	testSemver100 = "1.0.0"
	testTagLatest = "latest"
	testTagDev    = "dev"
	testTagMain   = "main"
	testTagAlpha  = "alpha"
	testTagBeta   = "beta"
	testTagV002   = "v0.0.2"
	testTagV003   = "v0.0.3"
	testTagV007   = "v0.0.7"
	testTagV020   = "v0.2.0"

	// Artifact and component names.
	testNameSRE            = "sre"
	testNameGSBase         = "gs-base"
	testNameGSAE           = "gs-ae"
	testNameGSPlatform     = "gs-platform"
	testNameGitHub         = "github"
	testNameFluxCD         = "fluxcd"
	testNameGopls          = "gopls"
	testNamePython         = "python"
	testNamePlatform       = "platform"
	testNameCodeReviewer   = "code-reviewer"
	testNameCommitCommands = "commit-commands"
	testNameNonexistent    = "nonexistent"
	testNameMinimal        = "minimal"
	testNameTest           = "test"
	testKeywordKubernetes  = "kubernetes"
	testKindToolchain      = "toolchain"
	testValueHello         = "hello"
	testKeyName            = "name"
	testKeyAuthor          = "author"
	testKeyDescription     = "description"
	testKeyHomepage        = "homepage"
	testKeyKeywords        = "keywords"
	testKeyLicense         = "license"
	testKeyRepository      = "repository"
	testKeyTags            = "tags"
	testNameInitKubernetes = "init-kubernetes"

	// Metadata values.
	testAuthorGiantSwarmGmbH = "Giant Swarm GmbH"
	testAuthorGiantSwarm     = "Giant Swarm"
	testLicenseApache2       = "Apache-2.0"
	testDescSREPersonality   = "SRE personality"
	testDescGSSREPersonality = "Giant Swarm SRE personality"
	testDescGoToolchainKlaus = "Go toolchain for Klaus"
	testDescGoToolchain      = "Go toolchain"
	testDescGeneralPlugin    = "A general purpose plugin"
	testDescBasePlugin       = "Base plugin"
	testEmail                = "test@example.com"
	testEmailDev             = "dev@giantswarm.io"

	// Test case names.
	testCaseShortNameExplicitTag = "short name with explicit tag"

	// Registries, repositories, and references.
	testRegistryGSOCI         = "gsoci.azurecr.io"
	testRegistryLocal         = "localhost:5000"
	testRegistryPlugins       = "gsoci.azurecr.io/giantswarm/klaus-plugins"
	testRefToolchainGo        = "gsoci.azurecr.io/giantswarm/klaus-toolchains/go"
	testRefToolchainPython    = "gsoci.azurecr.io/giantswarm/klaus-toolchains/python"
	testRefPluginGSBase       = "gsoci.azurecr.io/giantswarm/klaus-plugins/gs-base"
	testRefPluginGSSRE        = "gsoci.azurecr.io/giantswarm/klaus-plugins/gs-sre"
	testRefPluginGSAEV002     = "gsoci.azurecr.io/giantswarm/klaus-plugins/gs-ae:v0.0.2"
	testRefPluginGSAEV003     = "gsoci.azurecr.io/giantswarm/klaus-plugins/gs-ae:v0.0.3"
	testRepoPluginGSBase      = "giantswarm/klaus-plugins/gs-base"
	testRepoPluginGSPlatform  = "giantswarm/klaus-plugins/gs-platform"
	testRepoToolchainGo       = "giantswarm/klaus-toolchains/go"
	testRepoPersonalitySRE    = "giantswarm/klaus-personalities/sre"
	testOrgGiantSwarm         = "giantswarm"
	testRefExampleToolchainGo = "registry.example.com/toolchains/go"
	testRefExamplePluginTest  = "registry.example.com/plugins/test"
	testRefCustomPluginV200   = "custom.registry.io/org/my-plugin:v2.0.0"
	testRefOrgRepo            = "registry.io/org/repo"
	testRefLocalRepo          = "localhost:5000/repo"
	testRefLocalRepoV100      = "localhost:5000/repo:v1.0.0"
	testRefExampleRepo        = "example.com/repo"
	testRefExampleRepoV100    = "example.com/repo:v1.0.0"
	testRefExampleRepoDigest  = "example.com/repo@sha256:abc123"
	testPathV2                = "/v2"
	testPathV2Slash           = "/v2/"

	// Digests.
	testDigestAbc123       = "sha256:abc123"
	testDigestDef456       = "sha256:def456"
	testDigestAbc123Def456 = "sha256:abc123def456"

	// URLs.
	testSourcePersonalities = "https://github.com/giantswarm/klaus-personalities"
	testSourceKlausImages   = "https://github.com/giantswarm/klaus-images"
	testSourceClaudeCode    = "https://github.com/giantswarm/claude-code"
	testSourceGSBase        = "https://github.com/giantswarm/gs-base"
	testDocsURL             = "https://docs.giantswarm.io/klaus/"
	testHomeURL             = "https://giantswarm.io"
	testURLExample          = "https://example.com"
)
